export const authConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    AUTHENTICATED: 'AUTHENTICATED_USER',
    UNAUTHENTICATED: 'UNAUTHENTICATED_USER',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR'
};